### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BillsLate** [westonbattles/tiktok-webscraper#1]
Are your docs not working or? I'm interested in your project and got it to run on my discord bot but having the docs would be pretty nice

**Comment by westonbattles** [comment]
hey yeah, sorry I'm currently redesigning my website but I'll let you know when its back up

**Comment by BillsLate** [comment]
Thanks man, I did send over a email but didn't know if you got it or not. Project is great but I've had to do a little bit of additions to the code to separate some things so that the discord bot could fetch things individually such as the uniqueId and stuff but again, thank you
